name: Build Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish --configuration Release --runtime win-x64 --self-contained true
      
      - name: Compress artifacts
        run: zip -r RunDog_windows-x64.zip ./bin/Release/net8.0-windows/win-x64/publish/
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./RunDog_windows-x64.zip
          asset_name: RunDog_windows-x64.zip
          asset_content_type: application/zip